export enum TextForElement {
  Form = 'Welcome to Fun Chat! Please log in',
  HindLogin = 'Login must begin with a capital letter',
  HindPassword = 'Password must contain only numbers or English letters',
  HindLoginLength = 'Login length is less than 4 characters',
  HindPasswordLength = 'Password length is less than 6 characters',
  HeaderTitle = 'User',
  HeaderAppName = 'Fun Chat &#128516',
  BlockMessageStart = 'Select the user to send the message to...',
  BlockMessageDialog = 'Write your first message...',
  UserOnline = ' (online)',
  UserOffline = ' (offline)',
  BtnSent = 'Send',
  BtnLogin = 'Login',
  BtnInfo = 'Info',
  BtnLogout = 'Logout',
  BtnBack = '&larr;&nbsp;Back',
  InputSearch = 'Search...',
  InputMessage = 'Message...',
  lineNewMessage = 'New Message',
  ErrorConnectMessage = `Sorry, the connection to the server has been lost...<br> We're trying to reconnect...<br> Please wait...`,
  ListItemDelete = 'Delete',
  ListItemEdit = 'Edit',
  LinkGitHub = 'Link to',
  DescriptionInfoPage = 'The application was developed by student Irina Fileva as part of the RS School JS / Front-end course',
}

export enum ColorElement {
  Red = 'red',
  Black = 'black',
  Green = 'greenyellow',
}
